- name: Install necessary packages for Longhorn
  ansible.builtin.apt:
    name:
      - open-iscsi
      - nfs-common
      - bash
      - curl
      - grep
      - awk
      - lsblk
    state: present
    update_cache: yes

- name: Enable and start iscsid service
  ansible.builtin.systemd:
    name: iscsid
    enabled: true
    state: started
