- name: Check Kubernetes version
  ansible.builtin.shell: |
    kubectl version --output=json | jq -r '.serverVersion.gitVersion' | cut -c 2-
  register: kubernetes_version
  changed_when: false

- name: Fail if Kubernetes version is below minimum requirement
  ansible.builtin.fail:
    msg: "Kubernetes version {{ kubernetes_version.stdout }} is below the required version {{ kubernetes_min_version }}."
  when: kubernetes_version.stdout is version(kubernetes_min_version, '<')
